development:
  adapter: postgresql
  database: kozmeticar_devlopement
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: kozmeticar_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: kozmeticar_production
  pool: 5
  timeout: 5000
